spring:
  application:
    name: redis-distributed-lock-demo
  redis:
    host: localhost
    port: 6379
    jedis:
      max-idle: 16
      max-active: 32
      min-idle: 8

server:
  port: 8080
  servlet:
    context-path: /distributedLock